// app/src/views/includes/dynamic/Header/index.svelte
<script>
  import useMenu from "@hooks/useMenu";
  import Links from "@includes/dynamic/Header/Links.svelte";
  import Favicon from "@includes/dynamic/Header/Favicon.svelte";

  const { toggleMenu } = useMenu();

  export let header = {
    links: [
        {
            name: "",
            url: ""
        }
    ],
    favicon: {
        image: {

        },
        url: ""
    },
  };
</script>

<header class="container fixed z-20 w-full mx-auto overflow-hidden">
  <div class="flex items-center justify-between px-4 py-5">
    <Favicon/>

    <div class="w-auto">
      <div class="flex flex-wrap items-center">
        <Links  />

        <div
          class="hidden w-auto lg:block snipcart-customer-signin snipcart-checkout"
        >
          <div
            class="w-full px-5 py-3 font-semibold text-white transition duration-200 ease-in-out bg-green-700 bg-opacity-25 border border-gray-200 cursor-pointer snipcart-customer-signin rounded-xl focus:ring focus:ring-green-300 hover:bg-green-700"
          >
            🛒Cart
          </div>
        </div>
        <div on:click={() => toggleMenu()} class="w-auto ml-2">
          <a href="#">
            <svg
              class="text-green-700 navbar-burger"
              width="51"
              height="51"
              viewBox="0 0 56 56"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <rect width="56" height="56" rx="28" fill="currentColor" />
              <path
                d="M37 32H19M37 24H19"
                stroke="white"
                stroke-width="1.5"
                stroke-linecap="round"
                stroke-linejoin="round"
              />
            </svg>
          </a>
        </div>
      </div>
    </div>
  </div>
</header>

// app/src/views/includes/Header/Header.tsx
import Banner from "@views/components/dynamic/Banner";

import Headroom from "react-headroom";
import type { HeaderProps } from "@typings/Header";
import ButtonsSx from "@views/styles/Buttons";

const Header = ({ favicon, links, banner }: HeaderProps) => {


  const Favicon = () => {

    return (

      favicon ?
        <a className="flex-shrink-0 text-3xl font-bold font-heading" href="/">
          <img
            className="h-20"
            src={"/assets/images/logo.png"}
            alt={favicon?.image?.alt}
            width="auto"
          />
        </a> : <></>


    )
  }

  const NavLinks = () => {

    const buttonStyle = ButtonsSx().tw()

    return (
      links ? <ul className="hidden lg:flex lg:items-center lg:justify-center lg:w-full lg:m-auto ">
        {
          links.map((link, index) => {
            return (
              <li className="ml-5 mr-5 duration-200 ease-in hover:scale-90" key={index}>

                <a className={buttonStyle} href={link?.url}>
                  <span>
                    <img className="inline-block h-4 hvr-pop" loading="eager" src="/assets/images/dark-leaf.svg" />
                    {link?.name}
                  </span>

                </a>
              </li>
            )
          })
        }


      </ul> : <></>
    )
  }


  return (

    <Headroom>
      <section className="relative w-full bg-transparent outline-none backdrop-blur-xl">
        <Banner {...banner} />
        <nav className="relative flex justify-between">
          <div className="flex items-center w-full px-12 py-6">
            <Favicon />
            <NavLinks />
          </div>
          <a className="self-center mr-12 transition-all cursor-pointer navbar-burger hover:scale-110 duration-250">
            <img className="inline-block h-10 mr-1 hvr-pop" src="/assets/images/dark-leaf.svg" />
          </a>
        </nav>
      </section>
    </Headroom>

  )
}

export default Header
