// app/src/views/includes/dynamic/Header/Links.tsx
import type { LinkProps } from "@typings/Link"

export interface ILink {
  links?: LinkProps[]
}

export const defaultProps = {
  links: [...new Array(6).map(i => ({
    url: `${i}_NOT_FOUND`,
    name: 'URL_NAME_NOT_FOUND'
  }))]
}

const heading = ""
export default function Links({ links }: ILink) {

  return (
    <div className="hidden w-auto lg:block">
      <ul className="flex items-center mr-16">
        {
          links.map((link) => (
            <li
              className="font-thin font-serif uppercase underline-offset-4 shadow-black text-shadow-md rounded-md hover:shadow-2xl mr-9 hover:text-gray-700"
            >
              <a href={link?.url}>{link?.name}</a>
            </li>
          ))
        }
      </ul>
    </div>

  )
}

// app/src/views/includes/dynamic/Header/Links.svelte
<script>
  export let links = [
    {
        name: "NOT",
        url: ""
    }
  ];
</script>

<div class="hidden w-auto lg:block">
  <ul class="flex items-center mr-16">
    {#each links as link}
      <li
        class="font-medium rounded-md hover:shadow-2xl mr-9 hover:text-gray-700"
      >
        <a href={link.url}>{link.name}</a>
      </li>
    {/each}
  </ul>
</div>
